---
- hosts:        localhost
  connection:   local
  gather_facts: no
  
  tasks:
    - name: Setup Testing Variables
      include_vars: ./test/test-vars-artifactoryRepo.yml
      when: meta is undefined
  
    - name: Generate variables
      set_fact:
        project_plate: "{{ meta.namespace | regex_replace('\\-tools$|-dev$|-test$|-prod$', '')}}"

    - import_role:
        name: "artifactory_repo"
