apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |-
      Template for creating the artifactory operator deployment
  name: artifactory-operator-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: ${NAME}
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        serviceAccountName: ${NAME}
        containers:
          - name: ansible
            command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
            # Replace this with the built image name
            image: "${IMAGE_REGISTRY}/${IMAGE}:${IMAGE_TAG}"
            imagePullPolicy: "Always"
            volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true
#            - mountPath: /tmp/ansible-operator/
#              name: artifactory-secret
#              readOnly: true
          - name: operator
            # Replace this with the built image name
            image: "${IMAGE_REGISTRY}/${IMAGE}:${IMAGE_TAG}"
            #imagePullPolicy: "Always"
            volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
            - mountPath: /tmp/ansible-operator/
              name: artifactory-secret
              readOnly: true
            env:
              - name: ARTIFACTORY_BASE_DNS
                value: ${ARTIFACTORY_BASE_DNS}
              - name: ARTIFACTORY_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: WATCH_NAMESPACE
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: ${NAME}
        volumes:
          - name: runner
            emptyDir: {}
          - name: artifactory-secret
            secret:
              secretName: artifactory-admin
parameters:
- description: The name of the operator deployment
  displayName: Operator Name
  name: NAME
  value: "artifactory-operator"
- description: "The base DNS for the artifactory deployment (used to generate API URLs and docker routes)"
  displayName: Artifactory base DNS
  name: ARTIFACTORY_BASE_DNS
  value: artifacts.lab.pathfinder.gov.bc.ca
- description: "Image Registry string eg: docker-registry.default.svc:5000"
  displayName: Image Registry
  name: IMAGE_REGISTRY
  value: "docker-registry.default.svc:5000"
- description: "Image path as namespace/image-name"
  displayName: Image path
  name: IMAGE
  value: "devops-artifactory/artifactory-operator"
- description: "Image tag to use"
  displayName: Image tag
  name: IMAGE_TAG
  value: "v3.2-stable"
