---

- hosts:        localhost
  connection:   local
  gather_facts: no
  
  tasks:
    - name: Setup Testing Variables
      include_vars: ../test/test-vars-artifactorySA.yml
      when: meta is undefined

    - name: Set CR Variables
      set_fact:
        admin_pass_loc: "{{ testPass | default('/tmp/ansible-operator/admin/password') }}"
        artifactory_namespace: "{{ lookup('env', 'ARTIFACTORY_NAMESPACE')}}"
        project_plate: "{{ meta.namespace | regex_replace('\\-tools$|-dev$|-test$|-prod$', '')}}"
        license_plate: "{{ lookup('password', '/dev/null length=6 chars=ascii_letters') | lower }}"

    - name: Set Art URL and SA name
      set_fact:
        artifactory_url: "{{ test_url | default('http://artifactory-ha.{{ artifactory_namespace }}.svc.cluster.local:8081') }}"
        service_account_name: "{{ sa_name | default('{{ meta.name }}-{{ project_plate }}-{{ license_plate }}', true) }}"
    
    - import_role:
        name: "artifactory_serviceacct"
      when: (sa_name is defined) and (sa_name|length > 0)
  
    - name: Update CR ServiceAccount detail
      k8s:
        state: present
        definition:
          apiVersion: v1alpha1
          kind: ArtifactoryServiceAccount
          metadata:
            name: "{{ meta.name }}"
            namespace: "{{ meta.namespace }}"
          spec:
            sa_name: "{{ service_account_name }}"
            descriptor: "{{ descriptor }}"
      when: (sa_name is not defined) or (sa_name|length == 0)
  
    # - block:
    #   - name: "End when SA name not generated"
    #     debug:
    #       msg: "Generated SA_NAME."
    #   - meta: end_play
    #   when: (sa_name is not defined) or (sa_name|length == 0)
  
