---
- hosts:        localhost
  connection:   local
  gather_facts: no
  tasks:
  - name: deploy CRDs
    k8s:
      state: "{{ state | default('present') }}"
      src: ../config/crd/bases/{{ item }}
    with_items:
      - artifactory.devops.gov.bc.ca_artifactoryrepos.yaml
      - artifactory.devops.gov.bc.ca_artifactorysas.yaml

  - name: deploy Cluster Roles
    k8s:
      state: "{{ state | default('present') }}"
      src: ../config/rbac/{{ item }}
    with_items:
      - cr-aggregate-artifactrepos-view.yaml
      - cr-aggregate-artifactsvcas-admin-edit.yaml
      - cr-aggregate-artifactsvcas-view.yaml
      - cr-artifactory-cluster-operator.yaml
      - cr-artifactory-object-admin.yaml

  - name: deploy Cluster RoleBindings
    command: >
      oc adm policy add-cluster-role-to-user {{ item.clusterrole }} system:serviceaccount:{{ item.namespace }}:{{ item.serviceaccount }}
    with_items:
      - { clusterrole: "artifactory-cluster-operator", namespace: "{{ namespace }}", serviceaccount: "{{ svcAcct }}" }
      - { clusterrole: "artifactory-object-admin", namespace: "openshift", serviceaccount: "bcdevops-admin" }

  - name: deploy Project Roles
    k8s:
      state: "{{ state | default('present') }}"
      definition:  "{{ lookup('template', '../config/rbac/r-artifactory-operator.yaml.j2') }}"

  - name: deploy Project RoleBindings
    command: >
      oc adm policy add-role-to-user artifactory-operator system:serviceaccount:{{ item.namespace }}:{{ item.serviceaccount }} --role-namespace={{ item.namespace }}
    with_items:
      - { namespace: "{{ namespace }}", serviceaccount: "{{ svcAcct }}" }
      - { namespace: "openshift", serviceaccount: "bcdevops-admin" }
