---
- name: Create route for docker registry
  k8s:
    state: present
    namespace: "{{ artifactory_namespace }}"
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        labels:
          app: artifactory-ha
        name: "{{ team_name }}-{{ repository_type }}-{{ repository_locator }}"
      spec:
        host: "{{ team_name }}-{{ repository_type }}-{{ repository_locator }}.{{ external_dns_suffix }}"
        port:
          targetPort: router
        tls:
          insecureEdgeTerminationPolicy: Redirect
          termination: edge
          certificate: "{{ lookup('file', '{{ docker_cert_loc }}') }}"
          key: "{{ lookup('file', '{{ docker_private_key_loc }}') }}"
          caCertificate: "{{ lookup('file', '{{ docker_cert_ca_loc }}') }}"
        to:
          kind: Service
          name: artifactory-ha
          weight: 100
        wildcardPolicy: None

# # Add Docker Image Pull Secret to be used as a sample.

# - name: Find secret if exists
#   k8s_facts:
#     api_version: v1
#     kind: Secret
#     name: "{{ team_name }}-{{ repository_type }}-{{ repository_locator }}"
#     namespace: "{{ meta.namespace }}"
#   register: admin_secret
#   ignore_errors: yes

# - set_fact:
#     token: "{{ token_gen.json.access_token | b64encode }}"
#   when: admin_secret.resources == []

# - name: Create Admin Image Pull secret
#   k8s:
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: "{{ team_name }}-{{ repository_type }}-{{ repository_locator }}"
#         namespace: "{{ meta.namespace }}"
#       type: Opaque
#       data:
#         password: "{{ token }}"
#   when: admin_secret.resources == []
