- hosts: localhost
  vars_files:
    vars.yaml
  tasks:

      # setup
    - name: make sure we're in the artifactory namespace
      command: >
        oc project devops-artifactory

      # make storage
    - name: process 00-patroni-pgsql-prereq
      command: >
        oc process -f ./00-patroni-pgsql-prereq.yaml --param-file=./{{env}}-artifactory-ha.env --ignore-unknown-parameters=true
      register: storage_prereq_processed
    - copy: content="{{ storage_prereq_processed.stdout }}" dest=./processed/00-patroni-pgsql-prereq.json
    - name: apply 00-patroni-pgsql-prereq
      command: >
        oc apply -f ./processed/00-patroni-pgsql-prereq.json

      # wait until they're done.
    - pause:
        prompt: "Hit enter to continue once the storage is fully provisioned"

      # deploy patroni stateful set
    - name: process 01-patroni-pgsql
      command: >
        oc process -f ./01-patroni-pgsql.yaml --param-file=./{{env}}-artifactory-ha.env --ignore-unknown-parameters=true
      register: storage_processed
    - copy: content="{{ storage_processed.stdout }}" dest=./processed/01-patroni-pgsql.json
    - name: apply 01-patroni-pgsql
      command: >
        oc apply -f ./processed/01-patroni-pgsql.json

      # wait until they're done.
    - pause:
        prompt: "Hit enter to continue once the patroni stateful set is fully deployed"

      # deploy artifactory helm chart
    - name: create template from helm chart
      command: >
        oc process -f ./02-artifactory-ha-pre.yaml --param-file=./{{env}}-artifactory-ha.env --ignore-unknown-parameters=true
      register: pre_processed
    - copy: content="{{ pre_processed.stdout }}" dest=./processed/02-artifactory-ha-pre.json
    - name: apply 02-artifactory-ha-pre
      command: >
        oc apply -f ./processed/02-artifactory-ha-pre.json

