security:
  oauthSettings:
    persistUsers: true
    allowUserToAccessProfile: true
    enableIntegration: true
    oauthProvidersSettings:
      devhub-sso:
        id: artifactory-oauth
        enabled: true
        apiUrl: "https://sso.pathfinder.gov.bc.ca/auth/realms/devhub/protocol/openid-connect/userinfo"
        authUrl: "https://sso.pathfinder.gov.bc.ca/auth/realms/devhub/protocol/openid-connect/auth"
        basicUrl: "https://sso.pathfinder.gov.bc.ca/"
        providerType: github
        secret: xxxxxxxxxxxxxxxxxxxx
        tokenUrl: "https://sso.pathfinder.gov.bc.ca/auth/realms/devhub/protocol/openid-connect/token"
