artifactory:
  name: "artifactory"
  image:
    version: "7.4.3"
  masterKey: 3d5ffc86f2958dd644a882fc470b553cf599289a0bcd017f3d7ca3efa504a294
  joinKey: d13dcdf2c294ee083075b04cf15526ee8059521483d66aede74018c21665de1d
  primary:
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "3Gi"
        cpu: "3"
    javaOpts:
      xms: "2g"
      xmx: "2g"
  node:
    replicaCount: 0
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "2Gi"
        cpu: "2"
    javaOpts:
      xms: "2g"
      xmx: "2g"
  uid: 1000680000
  persistence:
    name: artifactory
    size: 10Gi
  service:
    pool: "all"
securityContext:
  enabled: true
  fsGroup: 1000680000
  runAsUser: 1000680000
postgresql:
  enabled: false
#  persistence:
#    enabled: true
#    size: 10Gi
nginx:
  enabled: false
#  uid: 1000680000
#  gid: 1000680000
database:
  type: postgresql
  driver: org.postgresql.Driver
  url: jdbc:postgresql://postgresql-master:5432/artifactory
  user: artifactory

