apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: artifactory-sa-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - artifactorySAs
  - pods
  - configmaps
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - '*'

