apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifactory-cluster-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - "route.openshift.io"
  resources:
  - 'routes'
  verbs:
  - list
  - watch
- apiGroups:
  - artifactory.devops.gov.bc.ca
  resources:
  - '*'
  verbs:
  - '*'
