kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-artifactsvcas-admin-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - artifactory.devops.gov.bc.ca
  resources:
  - artifactoryserviceaccounts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
