kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-artifactsvcas-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
rules:
- apiGroups: ["artifactory.devops.gov.bc.ca"]
  resources: ["ArtifactoryServiceAccount"]
  verbs: ["get", "list", "watch"]
