apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: requestron
labels:
  template: requestron-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
    labels:
      app: requestron
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
    labels:
      app: requestron
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: ${NAME}${VERSION}
          name: ${NAME}
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
          env:
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: GITHUB_PRIVATE_KEY
          - name: WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: GITHUB_WEBHOOK_SECRET
          - name: WEBHOOK_PROXY_URL
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: GITHUB_WEBHOOK_URL
          - name: ZENHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: ZENHUB_TOKEN
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: GITHUB_TOKEN
          - name: INSTALLATION_ID
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: GITHUB_INSTALLATION_ID
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: GITHUB_CLIENT_ID
          - name: REPO_NAME
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: REPO_NAME
          - name: REPO_OWNER
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: REPO_OWNER
          - name: APP_ID
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: APP_ID
          - name: REQUEST_REPO_ID
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: REQUEST_REPO_ID
          - name: SG_REPO_ID
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: SG_REPO_ID
          - name: SG_REPO_NAME
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: SG_REPO_NAME
          - name: ENVIRO
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: ENV
          - name: APP_NAME
            valueFrom:
              secretKeyRef:
                name: requestron-secrets
                key: APP_NAME
          - name: OPS_TEAM_ORG
            value: ${OPS_TEAM_ORG_VALUE}
          - name: OPS_TEAM_NAME
            value: ${OPS_TEAM_NAME_VALUE}
          - name: TZ
            value: America/Vancouver
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
    labels:
      app: requestron
  spec:
    ports:
    - name: api
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
    labels:
      app: requestron
  spec:
    host:
    port:
      targetPort: api
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: requestron
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: github ID of the request repo
  displayName: repo id value
  name: REPO_ID_VALUE
  required: true
  value: "219808631"
- description: application ID
  displayName: app id
  name: APP_ID_VALUE
  required: true
  value: "46693"
- description: team org
  displayName: team org
  name: OPS_TEAM_ORG_VALUE
  required: true
  value: "BCDevOps"
- description: team name
  displayName: team name
  name: OPS_TEAM_NAME_VALUE
  required: true
  value: "devops-request"
- description: webhook proxy url
  displayName: webhook proxy url
  name: WEBHOOK_PROXY_URL_VALUE
  required: true
  value: "https://smee.io/kaZCGksf7N5jrl"
