apiVersion: v1
kind: Secret
metadata:
  name: requestron-secrets
  labels:
    app: requestron
stringData:
  APP_ID: '46693' #probot needs an app ID to connect to the right github app
  APP_NAME: 'requestron' #the name of the app on Github
  ENV: 'test'
  GITHUB_CLIENT_ID: 'xxxxxxxxxxx' #for hitting the github API
  GITHUB_INSTALLATION_ID: 'xxxxxxxxxxx' #for hitting the github API - get this from an incoming webhook
  GITHUB_PRIVATE_KEY: xxxxxxxxxxx #probot needs this to authenticate to the right github app, this needs to be base64 encoded.
  GITHUB_TOKEN: 'xxxxxxxxxxx' #for hitting the github API
  GITHUB_WEBHOOK_SECRET: 'xxxxxxxxxxx' #this is for connecting to the smee url below
  GITHUB_WEBHOOK_URL: 'https://smee.io/9KmoAuGlmHDYilAq' #this smee provides webhook access
  REPO_NAME: 'devops-requests' #name of the repo to track
  REPO_OWNER: 'BCDevOps' #name of the org that owns the repo
  REQUEST_REPO_ID: '219808631' #zenhub needs the numerical repo ID for devops-requests
  SG_REPO_ID: '220104031' #zenhub needs the numerical repo ID for the sprint goal, usually developer-experience
  SG_REPO_NAME: 'developer-experience'
  ZENHUB_TOKEN: 'xxxxxxxxxxx' #for hitting the zenhub API


