- hosts: localhost
  vars_files:
    vars.yaml
  tasks:

      # setup
    - name: make sure we're in the artifactory namespace
      command: >
        oc project devops-artifactory
    - name: backup stateful set definition 1
      command: >
        oc get statefulset artifactory-primary -n devops-artifactory -o yaml
      register: def1
    - copy: content="{{ def1.stdout }}" dest=backup/artifactory-primary.yaml
    - name: backup stateful set definition 2
      command: >
        oc get statefulset artifactory-member -n devops-artifactory -o yaml
      register: def2
      when: env == 'prod'
    - copy: content="{{ def2.stdout }}" dest=backup/artifactory-member.yaml
      when: env == 'prod'

      # patch primary
    - name: patch primary
      command: >
        oc patch statefulset artifactory-primary -n devops-artifactory --type=json -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"docker.bintray.io/jfrog/artifactory-pro:{{version}}"}]'
    - pause:
        prompt: "Hit enter to continue once the primary patch has been completed"

      # patch secondary
    - name: patch secondary
      command: >
        oc patch statefulset artifactory-member -n devops-artifactory --type=json -p '[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"docker.bintray.io/jfrog/artifactory-pro:{{version}}"}]'
      when: env == 'prod'
