---
- hosts:        localhost
  connection:   local
  gather_facts: no
  tasks:

#  - name: create buildConfig? or run local build/push of image?

  - name: Create Operator Deployment
    k8s:
      state: "{{ state | default('present') }}"
      definition: "{{ lookup('template', '../config/manager/d-artifactory-operator.yaml.j2') }}"


