apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: artifactory
  name: artifactory-ha
labels:
  app.kubernetes.io/component: app
  app.kubernetes.io/name: artifactory
  app.kubernetes.io/managed-by: template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${ARTIFACTORY_NAME}
    annotations:
    name: ${ARTIFACTORY_NAME}-admin
  stringData:
    password: ${ARTIFACTORY_ADMIN_PASSWORD}
parameters:
- name: ARTIFACTORY_ADMIN_PASSWORD
  required: true
  value: app
- description: Artifactory name
  name: ARTIFACTORY_NAME
  value: "artifactory-ha"
  required: true
