apiVersion: v1
kind: Template
metadata:
  name: ${ARTIFACTORY_NAME}-template
  annotations:
    description: "Template to create Artifactory HA post-install objects"
objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${ARTIFACTORY_NAME}
      component: artifactory-ha
    name: artifactory
  spec:
    host: ${URL}
    port:
        targetPort: 8082
    tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: ${ARTIFACTORY_NAME}

parameters:
- description: Artifactory DNS Suffix
  name: URL
  value: "artifacts.lab.pathfinder.gov.bc.ca"
  required: true
- description: Artifactory name
  name: ARTIFACTORY_NAME
  value: "artifactory-ha"
  required: true
