---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for artifactory.operators.bcgov/v1alpha1, Kind: ArtifactoryRepo
  ##
  - apiGroups:
      - artifactory.operators.bcgov
    resources:
      - artifactoryrepoes
      - artifactoryrepoes/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for artifactory.operators.bcgov/v1alpha1, Kind: ArtifactorySA
  ##
  - apiGroups:
      - artifactory.operators.bcgov
    resources:
      - artifactorysas
      - artifactorysas/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
